name: Compose

on:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    # need checkout before using compose-action
    - uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./docker/docker-compose.yml"
